#ifndef TESTBUILDERS_WORKSHOP_ID_GENERATOR_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_ID_GENERATOR_H_INCLUDED

namespace id_generator
{
	int nextId();
}

#endif // TESTBUILDERS_WORKSHOP_ID_GENERATOR_H_INCLUDED