#ifndef TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_CATEGORY_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_CATEGORY_H_INCLUDED

namespace domain
{
namespace book
{
	enum Category {
		BUSINESS,
		LANGUAGE,
		COMPUTER
	};
}
}

#endif // TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_CATEGORY_H_INCLUDED