#ifndef TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_GENRE_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_GENRE_H_INCLUDED

namespace domain
{
namespace book
{
	enum Genre {
		HORROR_FICTION,
		THRILLER,
		DARK_FANTASY,
		MYSTERY,
		ADVENTURE_FICTION,
		NON_FICTION,
		ROMANCE
	};
}
}

#endif // TESTBUILDERS_WORKSHOP_DOMAIN_BOOK_GENRE_H_INCLUDED
