#ifndef TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_CURRENCY_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_CURRENCY_H_INCLUDED

namespace domain
{
namespace country
{
	enum Currency {
		US_DOLLAR,
		AUSTRALIAN_DOLLAR,
		EURO,
		POUND_STERLING,
		YEN,
		RENMINBI
	};
}
}


#endif // TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_CURRENCY_H_INCLUDED