#ifndef TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_LANGUAGE_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_LANGUAGE_H_INCLUDED

namespace domain
{
namespace country
{

	enum Language {
		ENGLISH,
		FRENCH,
		SPANISH,
		JAPANESE,
		MANDARIN,
		ARABIC,
		GERMAN
	};
}
}

#endif // TESTBUILDERS_WORKSHOP_DOMAIN_COUNTRY_LANGUAGE_H_INCLUDED