name: Kotlin Build

on: 
  push:
    branches-ignore:
      - '*-from-video'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build the Kotlin porject with Gradle
      working-directory: kotlin
      run: ./gradlew build
 