name: Java - Maven

on: 
  push:
    paths:
      - 'java/**'
    branches-ignore:
      - '*-from-video'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        java-package: jdk
    - name: Build with Maven
      working-directory: java
      run: mvn --batch-mode --update-snapshots clean test
 